services:
  postgres:
    container_name: db
    image: postgres:15
    restart: always
    env_file:
      - ./../../envs/postgres.env
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labeling_user -d labeling_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
